hackthefuture/hackthefuture.github.com

index.html, next/index.html
I hope I did this right! Please approve.
=> Updates for the upcoming HtF

projects/beautify-html.js, projects/chess/editor.html, projects/chess/index.html, projects/index.html, projects/pong/editor.html
Fixes all of the 404 links and broken chess game on hackthefuture.org/projects
This section is currently linked from hackthefuture.org/software.html, the "How to come prepared" page.
I tested this with Apache running on localhost. This doesn't give any guarantee that it will work on the server that may have different permissions settings, but it'll surely be less broken than what has been there for the past few years.
=> Fix JavaScript projects page

about/index.html, index.html, media/index.html, next/index.html, press/index.html, software.html, sponsor/index.html, volunteer/faq.html, volunteer/index.html, volunteer/signup.html
This implements many of the changes discussed on the email thread. Namely :
* Fix any 404 links or stale text
* List date and location for HtF15
* Include two working videos from the MEDIA page
* Link past photo albums from Emily Ramos and Dave Bricetti
* Feature Valerie's HtF10 blog summary from ABOUT page, while keeping this easy to find
* Link to software.html instead of JavaScript projects/
* Revise all copyright notices to (c) 2011-2015
=> Fix broken links and stale messages, announce HtF 15

about/index.html, index.html, media/index.html, next/index.html, press/index.html, software.html, sponsor/index.html, volunteer/faq.html, volunteer/index.html, volunteer/signup.html
In the past, we had allowed some of the copyright notices to fall behind by years. This time, I'm only late by 16 days!
=> Update copyright notices to 2016

index.html, next/index.html
Let's keep our front page fresh after Hack the Future 15.
=> Mark HtF 15 done and HtF 16 TBD

index.html, next/index.html
Update website for HtF17 @The Tech in August, now that HtF16 is done.
=> Display Hack the Future 17 info on /next/

software.html
This is a chaotic station with many hackers, so get students to download and install their IDE ahead of time. Also link to the station-minecraft-mod Github project for further instructions that we wouldn't want to fit here.
=> Update software.html, telling hackers to download IntelliJ IDEA

next/index.html
Eventbrite event link went up as of Friday, August 12th.
=> Add Eventbrite link for HtF17

index.html, media/index.html, next/index.html
Now that HtF17 has completed, this updates the front page and /next/ to not appear stale.
This also adds a link to DaveB's HtF17 photo album.
=> Mark HtF17 done and HtF18 TBD

about/index.html, index.html, media/index.html, next/index.html, press/index.html, software/index.html, sponsor/index.html, volunteer/faq.html, volunteer/index.html, volunteer/signup.html
It's that time of the year again.
=> Update copyright notices to 2017

about/index.html, index.html, media/index.html, next/index.html, press/index.html, software/index.html, sponsor/index.html, volunteer/faq.html, volunteer/index.html, volunteer/signup.html
As suggested by DaveB in #39, this looks better than the existing regular dash or an em-dash.
=> Use en-dash in copyright footers

about/index.html, index.html
Learningtech.org is our fiscal agent, and part of the agreement is that we list ourselves as a <i>program</i> of Learningtech.org on various materials.
Here is a minimal edit. When we have time later we'll update the sponsors page too for the necessary donor info and 501(c)(3) procedures.
=> Display Learningtech.org as our fiscal sponsor

index.html, next/index.html
=> Mark HtF18 done and HtF19 TBD

next/index.html
We have a few more days until we post the Eventbrite notice. In the meantime, let's make sure the website doesn't appear stale!
=> Put a note up on /next/ for Hack the Future 19

software/index.html
We'll have a station using the Greenfoot Java IDE at HtF19.
=> Add blurb and links for Greenfoot

about/index.html, index.html, media/index.html, next/index.html, press/index.html, software/index.html, sponsor/index.html, volunteer/faq.html, volunteer/index.html, volunteer/signup.html
We probably should have done this back in January!
=> Update copyright notices to 2018

next/index.html
We broadcasted on the mailing list today, so update the website as well.
=> Add HtF21 Eventbrite link to /next/

index.html, next/index.html
Clean up the front page and /next/ while it's fresh on our minds.
=> Mark HtF 21 done

software/index.html
This branch fixes some stylization issues such as s/Sketchup/SketchUp and s/Javascript/JavaScript.
It also removes Stencyl and updates the Scratch entry to say Scratch/Snap!
=> Clean up the software page

index.html, next/index.html
Clean up /next/ and the front page.
=> Mark HtF22 done

about/index.html, index.html, media/index.html, next/index.html, press/index.html, software/index.html, sponsor/index.html, volunteer/faq.html, volunteer/index.html, volunteer/signup.html
Noticed it's almost about time!
=> Update copyright notices for 2019

index.html
This is the source of the error in the console
=> Fixes unsecure link to action for subscription form

index.html, next/index.html
This page is looking a bit stale so let's clean it up now that HtF23 has passed.
(I'm also aware the the medical information sheet needs to be updated to the new one we used, but that will be a separate pull request.)
=> Mark HtF23 done

media/index.html
I came across Kathy's photos in an email thread, then realized we haven't linked photos for the past four events.
This branch adds links to the albums that I could find.
=> Add links to HtF23 and HtF21 flickr photos

software/index.html
* This is overdue as we've long meant to add Swift to the list of software
* Noting it's our largest download, Trevor pointed out our second-largest download was problematic at HtF23, so adding key text there
* Other minor cleanups
=> Add Swift and other download notes

index.html, next/index.html
Great event! Now let's clean up this page to make it current until we find a date and location for HtF25.
=> Mark HtF 24 done on /next/

about/index.html, index.html, media/index.html, next/index.html, press/index.html, software/index.html, sponsor/index.html, volunteer/faq.html, volunteer/index.html, volunteer/signup.html
=> Update copyright footer to 2020

about/index.html, index.html, media/index.html, next/index.html, press/index.html, software/index.html, sponsor/index.html, volunteer/faq.html, volunteer/index.html, volunteer/signup.html
Similar to #81 and #67. We'll automate this someday!
=> Update copyright footer to 2021
